services:
  # 1. Cấu hình Máy chủ API Backend (Flask)
  - type: web
    name: vsdat-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    rootDir: backend
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production

  # 2. Cấu hình Trang Web Frontend (React Vite)
  - type: web
    name: vsdat-frontend
    env: node
    static: true
    buildCommand: "npm install && npm run build"
    publishPath: dist
    rootDir: frontend
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: vsdat-backend
          property: exthost
